<div class="right-content">
    <div class="content">
        <table>
            <col width="2%">
            <col width="64%">
            <col width="15%">
            <col width="3%">
            <col width="6%">
            <tr>
                <th>Id</th>
                <th>Alias</th>
                <th>Date</th>
                <th>Published</th>
                <th>Actions</th>
            </tr>
            <?php
            if(isset($this->articles)) {
                foreach ($this->articles as $article) {
                    echo "<tr><td>";
                    echo $this->escape($article['id']);
                    echo "</td><td>";
                    echo $this->escape($article['alias']);
                    echo "</td><td>";
                    echo $this->escape($article['publishing_date']);
                    echo "</td><td>";
                    echo $this->escape($article['published']);
                    echo "</td><td>";
                    echo "<a class='half' href='edit/".$this->escape($article['id'])."'><i class=\"far fa-edit center\"></i></a> ";
                    echo "<a class='half' href='delete/".$this->escape($article['id'])."'><i class=\"fas fa-times center\"></i></a>";
                    echo "</td></tr>";
                }
            }
            ?>
        </table>
    </div>
</div>
</body>