<div class="right-content">
    <div class="content">
        <form>
            <div class="cont-96">
                <div class="left">
                    <div class="header">
                        Article Settings
                    </div>
                    <div class="cont-content">
                        <input class="width100" type="text" name="title" id="title" placeholder="Title" value="<?php echo $this->escape($this->article->getTitle())?>"<br>
                        <input class="width100" type="text" name="alias" id="alias" placeholder="Alias" value="<?php echo $this->escape($this->article->getAlias())?>"><br>
                        <input class="width100" type="text" name="preview" id="preview" placeholder="Preview" value="<?php echo $this->escape($this->article->getPreview())?>"><br>
                        <input class="less" type="date" name="date-time" id="date-time" value="<?php echo $this->escape($this->article->getDate())?>"><br>
                        <input class="less" type="checkbox" name="published" id="published" value="1" <?php echo ($this->article->getPublished()==1 ? 'checked' : '');?>><div style="font-size:15px;display:inline;">Published</div><br>
                    </div>
                </div>
                <div class="right">
                    <div class="header">
                        HTML social integration
                    </div>
                    <div class="cont-content">
                        <div>
                            <div id="social-editor"><pre><code><?php echo $this->escape($this->article->getSocialComments())?><code></pre></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="cont-96">
                <div class="header">
                    Article body
                </div>
                <div class="cont-content">
                    <div>
                        <div id="article-editor">
                            <?php echo $this->article->getBody()?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="center">
                <button type="button" value="Submit" onClick='submitForm()'>Create</button>
            </div>
        </form>
    </div>
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.8.0/highlight.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.8.0/languages/go.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <script src="https://cdn.quilljs.com/1.3.5/quill.js"></script>
    <script>
        hljs.configure({   // optionally configure hljs
            languages: ['xml']
        });

        var articlequill = new Quill('#article-editor', {
            theme: 'snow'
        });

        var socialquill = new Quill('#social-editor', {
            theme: 'bubble',
            modules: {
                toolbar: false,
                syntax: true
            }
        });
    </script>
    <script>
        function submitForm() {
            var alias = $('#alias').val();
            var preview = $('#preview').val();
            var datetime = $('#date-time').val();
            var published = $('#published').val();
            var title = $('#title').val();
            var editor = $('#article-editor').find('.ql-editor').html();
            var social = socialquill.getText();

            var content = title + "<!--SPLITME-->" + editor + "<!--SPLITME-->" + social;
            $.ajax({
                type: "POST",
                url: window.location.href + "/save",
                data: "alias=" + encodeURIComponent(alias) + "&preview=" + encodeURIComponent(preview) + "&datetime=" + datetime + "&published=" + published + "&content=" + encodeURIComponent(content),
                success: function () {
                    //Add popup message and redirect to /articles
                    alert('success');
                }
            });
        }
    </script>
</div>
</body>
