<div class="right-content">
    <div class="content">
        <table>
            <col width="2%">
            <col width="64%">
            <col width="15%">
            <col width="3%">
            <col width="6%">
            <tr>
                <th>Id</th>
                <th>Alias</th>
                <th>Date</th>
                <th>Published</th>
                <th>Actions</th>
            </tr>
            <?php
            if(isset($this->articles)) {
                foreach ($this->articles as $article) {
                    echo "<tr><td>";
                    echo $this->escape($article['id']);
                    echo "</td><td>";
                    echo $this->escape($article['alias']);
                    echo "</td><td>";
                    echo $this->escape($article['publishing_date']);
                    echo "</td><td>";
                    echo $this->escape($article['published']);
                    echo "</td><td>";
                    echo "<a class='half' href='edit/".$this->escape($article['id'])."'><i class=\"far fa-edit center\"></i></a> ";
                    echo "<a class='half' onClick=\"reqDelete(".$this->escape($article['id']).")\"><i class=\"fas fa-times center\"></i></a>";
                    echo "</td></tr>";
                }
            }
            ?>
        </table>

        <script>
            function reqDelete(articleID) {
                $.ajax({
                    type: "POST",
                    url: "delete/".articleID,
                    success: function () {
                        $('#popup').show();
                        $('#popup #success').show();
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        $('#popup').show();
                        $('#popup #error').show();
                        alert(xhr.status);
                        alert(thrownError);
                    }
                });
            }

            function stay() {
                $('#popup').hide();
                $('#popup #success').hide();
                $('#popup #error').hide();
            }
        </script>
    </div>
</div>
<div id="popup" class="popup" style="display:none">
    <div class="center-box full-width no-border">
        <div align="center">
            <div id="success" class="title" style="display:none">Success!</div><br>
            <div id="error" class="title" style="display:none">Error!</div><br>
            <button class="button" type="button" onClick='articleListRedirect()'>Back to the list</button>
        </div>
    </div>
</div>
</body>