    <div class="right-content">
        <div class="content">
            <div class="article">
                <form>
                    <div class="cont-96">
                        <div class="left">
                            <div class="header">
                                Article Settings
                            </div>
                            <div class="cont-content">
                                <input class="width100" type="text" name="title" id="title" placeholder="Title"><br>
                                <input class="width100" type="text" name="alias" id="alias" placeholder="Alias"><br>
                                <input class="width100" type="text" name="preview" id="preview" placeholder="Preview"><br>
                                <input class="less" type="date" name="date-time" id="date-time"><br>
                                <input class="less" type="checkbox" name="published" id="published" value="1"><div style="font-size:15px;display:inline;">Published</div><br>
                            </div>
                        </div>
                        <div class="right">
                            <div class="header">
                                HTML social integration
                            </div>
                            <div class="cont-content">
                                <div>
                                    <div id="social-editor"><pre><code class="xml jljs"><code></pre></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="cont-96">
                        <div class="header">
                            Article body
                        </div>
                        <div class="cont-content">
                            <div>
                                <div id="article-editor"></div>
                            </div>
                        </div>
                    </div>
                    <div class="center">
                        <button class="button" type="button" value="Submit" onClick='submitForm()'>Create</button>
                    </div>
                </form>
            </div>

            <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.8.0/highlight.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.8.0/languages/go.min.js"></script>
            <script>hljs.initHighlightingOnLoad();</script>
            <script src="https://cdn.quilljs.com/1.3.5/quill.js"></script>
            <script>

                hljs.configure({   // optionally configure hljs
                    languages: ['xml']
                });

                var articlequill = new Quill('#article-editor', {
                    theme: 'snow'
                });

                var socialquill = new Quill('#social-editor', {
                    theme: 'bubble',
                    modules: {
                        toolbar: false,
                        syntax: true
                    }
                });
            </script>
            <script>
                function submitForm() {
                    var alias = $('#alias').val();
                    var preview = $('#preview').val();
                    var datetime = $('#date-time').val();
                    var published = $('#published').val();
                    var title = $('#title').val();
                    var editor = $('#article-editor').find('.ql-editor').html();
                    var social = socialquill.getText();

                    var content = title + "<!--SPLITME-->" + editor + "<!--SPLITME-->" + social;
                    $.ajax({
                        type: "POST",
                        url: "new/save",
                        data: "alias=" + encodeURIComponent(alias)
                        + "&preview=" + encodeURIComponent(preview)
                        + "&datetime=" + datetime
                        + "&published=" + published
                        + "&content=" + encodeURIComponent(content),
                        success: function () {
                            $('#popup').show();
                            $('#popup #success').show();
                        },
                        error: function (xhr, ajaxOptions, thrownError) {
                            $('#popup').show();
                            $('#popup #error').show();
                            alert(xhr.status);
                            alert(thrownError);
                        }
                    });
                }

                function stay() {
                    $('#popup').hide();
                    $('#popup #success').hide();
                    $('#popup #error').hide();
                }

                function articleListRedirect() {
                    var r = window.location.href;
                    r = r.substr(0, r.indexOf("/new"));
                    window.location.replace(r + "/list");
                }
            </script>
        </div>
    </div>
    <div id="popup" class="popup" style="display:none">
        <div class="center-box full-width no-border">
            <div align="center">
                <div id="success" class="title" style="display:none">Success!</div><br>
                <div id="error" class="title" style="display:none">Error!</div><br>
                <button class="button" type="button" value="Submit" onClick='articleListRedirect()'>Article list</button>
            </div>
        </div>
    </div>
</body>