<div class="right-content">
    <div class="content">
        <form>
            <div class="cont-96">
                <div class="left">
                    <div class="header">
                        Article Settings
                    </div>
                    <div class="content">
                        <input class="width100" type="text" name="title" id="title" placeholder="Title"><br>
                        <input class="width100" type="text" name="alias" id="alias" placeholder="Alias"><br>
                        <input class="width100" type="text" name="preview" id="preview" placeholder="Preview"><br>
                        <input class="less" type="date" name="date-time" id="date-time"><br>
                        <input class="less" type="checkbox" name="published" id="published" value="1"><div style="font-size:15px;display:inline;">Published</div><br>
                    </div>
                </div>
                <div class="right">
                    <div class="header">
                        HTML social integration
                    </div>
                    <div class="content">
                        <div>
                            <div id="social-editor"><pre><code class="xml jljs"><code></pre></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="cont-96">
                <div class="header">
                    Article body
                </div>
                <div class="content">
                    <div>
                        <div id="article-editor"></div>
                    </div>
                </div>
            </div>
            <div class="center">
                <button type="button" value="Submit" onClick='submitForm()'>Create</button>
            </div>
        </form>
    </div>
    <script src="https://cdn.quilljs.com/1.3.5/quill.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.8.0/highlight.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.8.0/languages/go.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <script>

        hljs.configure({   // optionally configure hljs
            languages: ['xml']
        });

        var articlequill = new Quill('#article-editor', {
            theme: 'snow'
        });

        var socialquill = new Quill('#social-editor', {
            theme: 'bubble',
            modules: {
                toolbar: false,
                syntax: true
            }
        });
    </script>
    <style>
        .hljs{
            display:block;
            overflow-x:auto;
            padding:0.5em;
            background:#272822;
            color:#ddd
        }
        .hljs-tag,
        .hljs-keyword,
        .hljs-selector-tag,
        .hljs-literal,
        .hljs-strong,
        .hljs-name{
            color:#f92672
        }
        .hljs-code{
            color:#66d9ef
        }
        .hljs-class .hljs-title {
            color:white
        }
        .hljs-attribute,
        .hljs-symbol,
        .hljs-regexp,
        .hljs-link {
            color:#bf79db
        }
        .hljs-string,
        .hljs-bullet,
        .hljs-subst,
        .hljs-title,
        .hljs-section,
        .hljs-emphasis,
        .hljs-type,
        .hljs-built_in,
        .hljs-builtin-name,
        .hljs-selector-attr,
        .hljs-selector-pseudo,
        .hljs-addition,
        .hljs-variable,
        .hljs-template-tag,
        .hljs-template-variable{
            color:#a6e22e
        }
        .hljs-comment,
        .hljs-quote,
        .hljs-deletion,
        .hljs-meta{
            color:#75715e
        }
        .hljs-keyword,
        .hljs-selector-tag,
        .hljs-literal,
        .hljs-doctag,
        .hljs-title,
        .hljs-section,
        .hljs-type,
        .hljs-selector-id{
            font-weight:bold
        }
    </style>
    <script>
        function submitForm() {
            var alias = $('#alias').val();
            var preview = $('#preview').val();
            var datetime = $('#date-time').val();
            var published = $('#published').val();
            var title = $('#title').val();
            var editor = $('#article-editor').find('.ql-editor').html();
            var social = socialquill.getText();

            var content = title + "<!--SPLITME-->" + editor + "<!--SPLITME-->" + social;
            $.ajax({
                type: "POST",
                url: "new/save",
                data: "alias=" + encodeURIComponent(alias) + "&preview=" + encodeURIComponent(preview) + "&datetime=" + datetime + "&published=" + published + "&content=" + encodeURIComponent(content),
                success: function () {
                    //Add popup message and redirect to /articles
                    alert('success');
                }
            });
        }
    </script>
</div>
</body>